version: 2 # use CircleCI 2.0
jobs: # a collection of steps

  build: # runs not using Workflows must have a `build` job as entry point

    docker: # run the steps with Docker
      - image: circleci/node:10.15.1 # ...with this image as the primary container; this is where all `steps` will run

    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'

      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
      - restore_cache: # special step to restore the dependency cache
          name: Restore node_modules cache
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Nodejs Version
          command: node --version

      - run:
          name: Install Packages
          command: yarn install --frozen-lockfile

      - run: # run tests
          name: test
          command: npm test

      - save_cache: # special step to save the dependency cache
          name: Save node_modules cache
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - store_artifacts: # special step to save test results as as artifact
          # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
          path: test-results.xml
          prefix: tests

      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test-results.xml
